### ISSUE TITLE
Are off values being respected?

### ISSUE THREAD

**Issue by jmenglis** [prettier/prettier-eslint-cli#100]
- `prettier-eslint-cli` version: latest
- `prettier` version: latest
- `eslint` version: latest

Relevant code/config.

unlinted code ->
```javascript
"use strict";
const {foo} = bar
```

linted code:
```javascript
"use strict";
const { foo } = bar;
```

eslintrc.json
```javascript
{
  "extends": ["eslint:recommended"],
  "rules": {
    "semi": 0,
    "object-curly-spacing": 0
  }
}
```
What you did:
I ran both `node_modules\.bin\prettier-eslint *.js --write` and `node_modules\.bin\prettier-eslint *.js --write --eslint-config-path ./.eslintrc.json`.

What happened:

Both returned successfully and changed file from unlinted code to linted code but didn't follow the eslint rules above.  Which should have let the file unchanged for those specific rules.  This could potentially be a `prettier-eslint` issue I will test later today.

**Comment by kentcdodds** [comment]
Off values will not be `eslint --fix`ed, but prettier's going to do its thing one way or another.

So when you disable a rule, prettier-eslint will fallback to prettier's default. You can (as of today) use prettier's config or CLI flags to choose how you want prettier to deal with those things. See the prettier README for how to do that.

Good luck!

**Comment by jmenglis** [comment]
Thanks!
