### ISSUE TITLE
eslintignore

### ISSUE THREAD

**Issue by calebeby** [prettier/prettier-eslint-cli#101]
Hi,

It would be awesome if prettier-eslint would support ignoring files in the `eslintIgnore` field in the `package.json`

Here's the relevant docs: https://eslint.org/docs/user-guide/configuring#using-eslintignore-in-packagejson

**Comment by kentcdodds** [comment]
Thanks for the idea! Sounds like that'd be useful! Feel free to [make a pull request](http://makeapullrequest.com) 😀

**Comment by calebeby** [comment]
I figured you'd ask :smile:
I looked at the code a bit, can you point me to which function I should add the logic to?

**Comment by kentcdodds** [comment]
Relevant code here:

https://github.com/prettier/prettier-eslint-cli/blob/0d101e4178a0649e8020dfafcd10124a9e6d34f1/src/format-files.js#L251-L264

Similar tests are here:

https://github.com/prettier/prettier-eslint-cli/blob/0d101e4178a0649e8020dfafcd10124a9e6d34f1/src/format-files.test.js#L192-L235

Good luck! And thanks :)

**Comment by calebeby** [comment]
I realized you were right about not needing this project, so I'm not going to create a PR for this. Feel free to close this if you want, or just let it open.
