### ISSUE TITLE
no `--prettier-config-path`?

### ISSUE THREAD

**Issue by ambar** [prettier/prettier-eslint-cli#102]

**Comment by kentcdodds** [comment]
You should be able to just use `--config` flag... All unknown flags are passed to prettier.

**Comment by ambar** [comment]
`yargs` ignores unknown flag.

**Comment by neutraali** [comment]
`"prettier-eslint-cli": "4.7.1"`

I don't think this `--config` is working as intended. I tried giving it my `.prettierrc` filepath - `[DEBUG]` and `[TRACE]` never make a single mention of it. All my **prettierOptions** are either not set or inferred from `.eslintrc` - The case being that I have most options filled out (most notably **requirePragma**).

There's also a typo in the README adding to the confusion that lists `[default: "./node_modules/prettier"]` under `--config`; I think the intention is that it should be listed under `--prettier-path`.
