### ISSUE TITLE
TypeError: prettier.resolveConfig.sync is not a function

### ISSUE THREAD

**Issue by ppvg** [prettier/prettier-eslint-cli#105]
It looks like there is a regression in 4.3.2:

```console
$ node_modules/.bin/prettier-eslint path/to/file.js
prettier-eslint-cli [ERROR]: There was an error formatting "path/to/file.js":
    TypeError: prettier.resolveConfig.sync is not a function
        at getPrettierConfig (node_modules/prettier-eslint/dist/index.js:233:33)
        at format (node_modules/prettier-eslint/dist/index.js:90:51)
        at MapSubscriber.project (node_modules/prettier-eslint-cli/dist/format-files.js:275:55)
        at MapSubscriber._next (node_modules/rxjs/operator/map.js:77:35)
        at MapSubscriber.Subscriber.next (node_modules/rxjs/Subscriber.js:89:18)
        at AsyncSubject.Subject.next (node_modules/rxjs/Subject.js:55:25)
        at AsyncSubject.complete (node_modules/rxjs/AsyncSubject.js:46:35)
        at handlerFn (node_modules/rxjs/observable/BoundNodeCallbackObservable.js:193:33)
        at tryToString (fs.js:456:3)
        at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:443:12)
```

This only happens with <s>version 4.3.2, not with 4.3.1</s> versions 4.3.2 and 4.3.1, not with 4.3.0. 
It also happens without a `.prettierrc` file.

- `prettier-eslint-cli` version: 4.3.2
- `prettier-eslint` version: 8.0.0
- `eslint` version: 4.6.1

**Comment by keepitterron** [comment]
This commit is causing this error: https://github.com/prettier/prettier-eslint/commit/e39719e7e1cd830f16469f26910ec662c443fa9c

the function `resolveConfig.sync` does not seem to exist. I have the same error on a different `prettier-eslint-cli`

**Comment by kentcdodds** [comment]
Could you delete your `node_modules` and reinstall everything? My guess is that you have an old version of prettier... cc @robwise

**Comment by keepitterron** [comment]
I might be wrong, but this is the last commit for the prettier build: https://github.com/prettier/prettier/blob/c3506198c007e6667975b3dbf958b8b06550f4a8/website/static/lib/index.js

there is no `resolveConfig.sync`? I'm running prettier 1.6.1 which is the latest.
I have the same issue with `4.3.1` and not with `4.3.0`

**Comment by keepitterron** [comment]
Seems like the `.sync` methods get stripped out of the npm build somehow?

**Comment by marcbachmann** [comment]
@kentcdodds I don't think that the `resolveConfig.sync` is in the published prettier module yet.
That landed 7 days ago on master. https://github.com/prettier/prettier/pull/2722
The most recent release was 10 days ago.

**Comment by bardware** [comment]
Emptied my `node_modules`  folder follwed by `npm i` 
no help :(

**Comment by kentcdodds** [comment]
Ah yes, well that's a problem... cc @robwise 

I suggest locking down to `prettier-eslint-cli@4.3.0` until the next version of prettier gets released.

I'm not using `prettier-eslint` anymore (I'm just using `prettier`) so I'm afraid my time on the project is pretty limited. If someone wants to take up the torch let me know :)

**Comment by bardware** [comment]
> I'm not using prettier-eslint anymore (I'm just using prettier)

The eslint folks keeps insisting eslint is much more than a prettifier. I love to use both. Your tool combines them nicely.

**Comment by kentcdodds** [comment]
I use both as well, but I don't use eslint for formatting, I use it for catching bugs that cannot be autofixed :smile:

I'm glad you like my tool though!

**Comment by robwise** [comment]
double oops, sorry I totally didn't realize that wasn't part of the original resolveConfig release, I just read it in the manual and didn't even think to check

**Comment by diondirza** [comment]
just upgraded from 4.1.1 and the error occurred, seems 4.1.1 working fine without this error.

**Comment by bkw** [comment]
prettier-1.6.2 is (which will include prettier/prettier#2722) is about to be released faily soon, see prettier/prettier#2804.

**Comment by gb714us** [comment]
prettier 1.7.0 is out. They had to upgrade to a minor version.

**Comment by kentcdodds** [comment]
Thanks!

**Comment by bkw** [comment]
shouln't we bump the depenency on prettier-eslint here in cli?

**Comment by TroublemakerSt** [comment]
I upgraded prettier to 1.7.0 and nothing happened. What's wrong? Any idea?

**Comment by bkw** [comment]
In my case I had a yarn.lock preventing the update. I had to remove it.

**Comment by TroublemakerSt** [comment]
My mistake. In the project, there was an old version...
