### ISSUE TITLE
Ability to know if code is not formatted

### ISSUE THREAD

**Issue by bas080** [prettier/prettier-eslint-cli#107]
- `prettier-eslint-cli` version: 4.3.2
- `prettier` version: 1.7.0
- `eslint` version: 4.6.1

Problem description:

Prettier-eslint-cli does not return exit codes for when code is not formatted but is "format-able". In the pre commit I am currently doing something to get it to work regardless.

```bash
#!/usr/bin/env bash

git diff --name-only --staged '*.js' | while read source_file; do
  echo "Checking \"$source_file\"..."
  diff "$source_file" <(prettier-eslint "$source_file" 2> /dev/null) || exit 1
done
```
I am using the bash diff command to know if the formatted code is the same as the code in the file. This however causes the check to be slow because I can only perform one test at a time. I could use gnu' parallel command but it feels like overkill. One option in prettier-eslint-cli would make it much nicer and quicker.

Suggested solution:

What I would like is that `prettier-eslint-cli` exits with non zero code if the check determines that the code is format-able but not formatted.

In that case I could write the following in order to check if the code is formatted.

`prettier-eslint --check $(git diff --name-only --staged '*.js') && exit || echo "Please format your code" && exit 1`

The `--check` parameter would tell prettier-eslint-cli that it is checking if the files are formatted.

**Comment by kentcdodds** [comment]
Hi @bas080,

Sounds fine to me :+1: Feel free to [make a pull request](http://makeapullrequest.com)
