### ISSUE TITLE
How does this pick up .eslintrc, and merge it with any parent .eslintrc files?

### ISSUE THREAD

**Issue by wbern** [prettier/prettier-eslint-cli#110]
- `prettier-eslint-cli` version: latest
- `prettier` version: latest
- `eslint` version: latest

What you did:

`./node_modules/.bin/prettier-eslint --write src/myfile.js`

What happened:

I got a linted file with 2-spaces indentation, rather than 4-spaces which is specified in the parent directory's .eslintrc (not in the current directory .eslintrc)

I don't have a .prettierrc, but have also tried with an empty one.

Reproduction:

Try to change spacing via .eslintrc "indent" rule?

Problem description:

Does this package pick up .eslintrc rules? 

This VS Code extension does the job perfectly.
https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

However, I still want to use the CLI for this for pre-commit hooks.

Suggested solution:
Make it pick up .eslintrc and any parent .eslintrc files and use the preferred spacing in it.

**Comment by clawoflight** [comment]
Settings should totally be resolved from .eslintrc, that's the entire point of having that file.
