### ISSUE TITLE
Change success message to warning.

### ISSUE THREAD

**Issue by nikgraf** [prettier/prettier-eslint-cli#111]
-    "eslint": "^4.8.0",
-    "prettier-eslint": "^8.2.0",
-   "prettier-eslint-cli": "^4.4.0",

Relevant code/config.

```javascript

```

What you did:

What happened:

I'm using it in combination with lint-staged and husky to identify if files haven't been formatted with prettier-eslint.

The green success message although a diff was found is quite confusing.

![screen shot 2017-10-13 at 15 03 40](https://user-images.githubusercontent.com/223045/31547493-d2f25010-b027-11e7-8bc9-cdde6dbc79d4.png)

Once I replace prettier-eslint with prettier this is the CLI output prettier itself generates

![screen shot 2017-10-13 at 15 05 25](https://user-images.githubusercontent.com/223045/31547558-12b525a6-b028-11e7-8266-a91080be86f9.png)

**Comment by kentcdodds** [comment]
Hi @nikgraf!

I didn't implement the `--list-different` flag so I was unaware this was happening. PRs accepted. :+1:
