### ISSUE TITLE
I'm stepping down from the project.

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-eslint-cli#115]
Hey folks, so it's been a few months that I've not used this project anymore (I just use `prettier` now). So I will no longer be watching the repository and I'll also be removing the auto-release functionality. Someone else can set that up... on that note:

Who wants to take this project over? (I'll be doing the same for `prettier-eslint` https://github.com/prettier/prettier-eslint/issues/139). 

cc everyone who's committed code to the project: @BenoitZugmeyer, @bySabi, @mrm007, @ryanhiebert, @moretti, @RyanZim, @jackfranklin, @mvolkmann, @diondirza, @tunnckoCore, @MikeyBurkman, @jmenglis, @Gandem, @denis-sokolov, @spudly, @sheerun, @aaronjensen, @DirtyF, @joelseq, @ambar, @fredrikekelund, @morhetz, @cef62

**Comment by ryanhiebert** [comment]
I anticipate also just using prettier myself.

**Comment by kentcdodds** [comment]
If you want to maintain the project and have publish rights, give me your npm and github usernames and I'll hand it over to you. I'm afraid I [wont have time](http://kcd.im/no-time) to contribute or help out with this project any further. Good luck!

**Comment by kentcdodds** [comment]
@zimme has volunteered to take over.

I'll go ahead and close these issues on both repos and let @zimme decide who he'd like to give publish rights/commit rights to now :+1:

**Comment by zimme** [comment]
I don't know how much time I will have to put into this project, but as I am using it in a few projects I'd at least like to be able to fix bugs. I will happily split the responsibility with whom ever is interested in keeping the project maintained.

**Comment by jmenglis** [comment]
@zimme I would be able to help out here and there.  We use this project pretty heavily at work.

**Comment by zimme** [comment]
@kentcdodds I don't seem to have proper access to travis for this project.

**Comment by kentcdodds** [comment]
Hmmm... Let me figure out what's going on... I think I never added you as a collaborator to the CLI 😅

**Comment by zimme** [comment]
Aah, that would explain it 😄

**Comment by jmenglis** [comment]
@zimme let me know if you still need help on this and prettier-eslint
