### ISSUE TITLE
doesn't this cli match `.eslintrc` or `.eslinrc.js`

### ISSUE THREAD

**Issue by fanyer** [prettier/prettier-eslint-cli#120]
https://github.com/prettier/prettier-eslint-cli/blob/f70364daa3c081688d31ea3e99033e6944f75477/src/parser.js#L56-L59

Here seems no default value for eslint-config-path. 

When I use `pretter-atom` with `eslint integration` checked in. This should enable `prettier-eslint`. Then `prettier-eslint-cli` should work to format code.

strange things happened that It doesn't format according to my `.eslintrc`.
However, mannual format by `prettier-eslint  src/**/*.js` works normally.

So I supposed `prettier-eslint-cli` doesn't match my `.eslint` config. 

Can you give some guides for eslint integration with atom? I want to format  on save according to my `.eslintrc` config

**Comment by fanyer** [comment]
I've traced the `prettier-atom` plugin. It's because eslint local lost. Please ignore this issue. Blessing

**Comment by zimme** [comment]
`prettier-atom` use `prettier-eslint` directly and not this package. However I do believe there was a change in that package a while back which changed the config precedence.

I'll open an issue with `prettier-atom` to see what a good solution would be. I'm thinking that I might need to add an option to `prettier-eslint` to allow the editor integration to get the proper config with inferred config from eslint config files.
