### ISSUE TITLE
Validation Warning

### ISSUE THREAD

**Issue by Avcajaraville** [prettier/prettier-eslint-cli#121]
- `prettier-eslint-cli` version: 4.4.2
- `prettier` version:  1.9.2
- `eslint` version:  3.19.0

What you did:
 I have updated my personal project, bumping all my dependencies via `rm -R node_modules && npm install`.

My prettier-eslint-cli version was bumped from 4.1.0 to 4.4.2.

The way I run it, is through an npm script on my package.json, like:
```
"prettier": "npx prettier-eslint --ignore \"node_modules/**\" --ignore \"public/**\" --single-quote --trailing-comma es5 --write \"**/*.js\"",
```

So on the terminal, I run `npm run prettier`

What happened:

Since the update, everything is fine, but I get very annoying warning messages:

```
● Validation Warning:

  Unknown option "trailing-comma" with value "es5" was found. Did you mean "trailingComma"?
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "single-quote" with value true was found. Did you mean "singleQuote"?
  This is probably a typing mistake. Fixing it will remove this message.
```
<img width="862" alt="captura de pantalla 2017-12-12 12 31 14" src="https://user-images.githubusercontent.com/2271201/33882423-611a6f32-df38-11e7-8dac-54a8f91c6d46.png">

I have been struggling, searching for trailing-comma and single-quote on the whole project without success, I have been reading all possible documentation and changelog from prettier, prettier-eslint, prettier-cli, prettier-eslint-cli and eslint, I tried camel casing the options on the cli command, but I have no way of getting rid of this warning. 

Any idea ?

**Comment by zimme** [comment]
I believe it might be because of an upgrade of yargs. I'll look into it.

**Comment by Avcajaraville** [comment]
@zimme great ! Thanks, I'll wait for updates, on the meantime, I will downgrade my versions :)

**Comment by zimme** [comment]
`prettierOptions` needs to be stripped from all `kebab-case` options before used in `prettierESLintOptions` in the following lines.

https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L59-L68.

**Comment by zimme** [comment]
I'm thinking we should just be able to strip all `kebab-case` options before we invoke `formatFilesFromArgv` with the options from yarg's parser.

**Comment by Avcajaraville** [comment]
I tried to debug the reason why, but Im out of ideas. I tracked the issue to yargs, somehow, the call to the parser returns "single-quotes" & "trailing-comma" instead of just the camel case version (which is also returned).

Its the first time I read yargs api and so far is a bit confusing to me, as its my first time there.

One idea I had was to change the options keys passed to the parser, but that obviously breaks the cli api.

I believe there are two possible issues here: something is wrong in the validations, as it shouldn't validate the non camel case version; and the other possibly yargs generating wrong options. There should be a way of telling yargs to just use the camel case version and not return the kebap-case

**Comment by zimme** [comment]
This is because of a change I made in `prettier-eslint`, where before it only forwarded options from ´prettier-eslint-cli´ to `prettier` that we had configured in the eslint-to-prettier option inference step, but now it forwards all options that isn't specific `prettier-eslint-cli` options.

So I'll make a few changes in this package which filters the options to only include the camel cased versions before we forward them to `prettier-eslint´.

**Comment by zimme** [comment]
Thank you for taking the time to look into this. It helped me figure out where the problem lies a bit faster. Also, always nice to fix bugs.

**Comment by zimme** [comment]
@Avcajaraville Cold you test the latest version and see if the problem is solved?

**Comment by Avcajaraville** [comment]
@zimme amazing ! This works as expected ! Thanks for the quick and nice job :)
