### ISSUE TITLE
Validation Warnings appearing when running prettier

### ISSUE THREAD

**Issue by seanippolito** [prettier/prettier-eslint-cli#123]
"prettier": "1.9.2",
"prettier-eslint": "^8.5.0",
"eslint-config-prettier": "^2.9.0",
 "eslint": "^4.13.1",

ran a script npm run lint which is tied into my linter, flow checks, react checks and prettier. Results below.

● Validation Warning:

  Unknown option "definitions" with value {"optionsDefinition": {"properties": {"bracketSpacing": {"default": true, "de
scription": "Print spaces between brackets in object literals.", "type": "boolean"}, "jsxBracketSameLine": {"default":
false, "description": "Put the > of a multi-line JSX element at the end of the last line instead of being alone on the
next line.", "type": "boolean"}, "parser": {"default": "babylon", "description": "Specify which parser to use.", "enum"
: ["babylon", "flow", "typescript", "postcss", "json", "graphql"], "type": "string"}, "printWidth": {"default": 80, "de
scription": "Specify the line length that the printer will wrap on.", "type": "integer"}, "semi": {"default": true, "de
scription": "Print semicolons at the ends of statements.", "type": "boolean"}, "singleQuote": {"default": true, "descri
ption": "Use single quotes instead of double quotes.", "type": "boolean"}, "tabWidth": {"default": 2, "description": "S
pecify the number of spaces per indentation-level.", "type": "integer"}, "trailingComma": {"default": "none", "descript
ion": "Print trailing commas wherever possible.", "enum": ["none", "all", "es5"], "type": "string"}, "useTabs": {"defau
lt": false, "description": "Indent lines with tabs instead of spaces.", "type": "boolean"}}}, "overridesDefinition": {"
properties": {"overrides": {"description": "Provide a list of patterns to override prettier configuration.", "items": {
"additionalProperties": false, "properties": {"excludeFiles": {"description": "Exclude these files from this override."
, "oneOf": [{"type": "string"}, {"items": {"type": "string"}, "type": "array"}]}, "files": {"description": "Include the
se files in this override.", "oneOf": [{"type": "string"}, {"items": {"type": "string"}, "type": "array"}]}, "options":
 {"$ref": "#/definitions/optionsDefinition", "description": "The options to apply for this override.", "type": "object"
}}, "required": ["files"], "type": "object"}, "type": "array"}}}} was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "type" with value "object" was found.
  This is probably a typing mistake. Fixing it will remove this message.

● Validation Warning:

  Unknown option "allOf" with value [{"$ref": "#/definitions/optionsDefinition"}, {"$ref": "#/definitions/overridesDefi
nition"}] was found.
  This is probably a typing mistake. Fixing it will remove this message.

Problem description:
I would like to get rid of or ignore these warnings.

Suggested solution:
None

**Comment by zimme** [comment]
Could you give me the full command used when you get these warnings? I'm pretty surr this is related to how we're forwarding all options to prettier, except those specific to prettier-eslint.

**Comment by seanippolito** [comment]
Apologies for the late reply. I am using create-react-app with a webpack config. I use npm run lint which points to this line for execution ->     "lint": "esw webpack.config.* src tools --color". Does this help?

**Comment by zimme** [comment]
So I can't see that `esw`, which assume is `eslint-watch`, supports `prettier-eslint` so I'm thinking this is a problem with `eslint-watch` or `eslint`.

My first thought is that you're feeding all the files in the project to `eslint-watch` with that command and it errors out because it tries to format unsupported files.

I will need more information that this is really related to `prettier-eslint` before I can afford the time to look into this.

**Comment by seanippolito** [comment]
Ok I will close this issue. It may just be a conflict that I have from incorporating rules from different packages.

**Comment by Redmega** [comment]
prettier-eslint has changed its API I assume. I am facing this same issue, just running this command:
`prettier-eslint $files --write --tabWidth 2 --trailingComma all --bracketSpacing --semi --singleQuote --printWidth 100`

**Comment by tpict** [comment]
I ran some upgrades and have the same problem with:
- `prettier-eslint-cli` version: 4.7.0
- `prettier-eslint` version: 6.4.3
- `prettier` version: 1.10.2
- `eslint` version: 4.17.0

I downgraded packages to match a working setup on another machine:
- `prettier-eslint-cli` version: 4.1.1
- `prettier` version: 1.5.3
- `eslint` version: 3.19.0

**Comment by sQVe** [comment]
I'm having the same issues. I have the following in my `.prettierrc` file:
```
{
  "singleQuote": true,
  "trailingComma": "es5"
}
```
Currently running:
```
    "prettier": "^1.10.2",
    "prettier-eslint-cli": "^4.7.0",
```

I can reproduce the warning messages simply by running: `prettier-eslint --write '{**/*,*}.{js,jsx,json}'`. Gimme a ping if I can provide any further help/information.
