### ISSUE TITLE
Suggestion: continue to format files ignored by ESLint `.eslintignore`

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-eslint-cli#137]
Related: https://github.com/prettier/prettier-eslint-cli/issues/16

Using the `prettier-eslint` Node API, a file ignored by ESLint via `.eslintignore` will continue to be formatted by Prettier, but ESLint auto fixes will not be applied.

However, this behaviour is different for the CLI: the file is ignored completely, from both Prettier and ESLint.

What do you think about adopting the behaviour used by `prettier-eslint`?

**Comment by zimme** [comment]
Let's align on that behaviour. It's nice to ignore files separately and I believe that would align with using eslint and prettier one after another.
