### ISSUE TITLE
Support for multiple file arguments

### ISSUE THREAD

**Issue by tomleo** [prettier/prettier-eslint-cli#145]
- `prettier-eslint-cli` version: 4.7.1
- `prettier` version: 1.13.7
- `eslint` version: 4.19.1

Problem description: Can only pass a single file or a glob argument for processing

There's a lot of powerful command line tools that can be chained together to get the list of files I wish to format i.e. `find ./ -type f | awk -f front_end_files.awk` or if I only want "tracked" files I could do `git ls-files | awk -f front_end_files.awk`, if I only want to format staged files I could pass `--cached` to `ls-files`, ect. This list of files could then be passed as arguments to `prettier-eslint` something like:

``` bash
FRONTEND_FILES=$(find ./ -type f | awk -f utils/format_frontend.awk | paste -d ' ' -s -)
./frontend/node_modules/.bin/prettier-eslint $FRONTEND_FILES
```

However the only options currently available are glob or a single file at a time

Suggested solution:

Support for `prettier-eslint [FILE ...]` argument format.

**Comment by zimme** [comment]
`prettier-eslint-cli` supports the following syntax
```
> prettier-eslint "some.file" "another.file" "src/**/*.js"
```

So multiple files should be supported.

**Comment by zimme** [comment]
In your case I do believe you might need to use something like `xargs` to pipe the list of files to `prettier-eslint`, maybe?
