### ISSUE TITLE
Report invalid eslint rule (would generally like more feedback)

### ISSUE THREAD

**Issue by devinrhode2** [prettier/prettier-eslint-cli#146]
- `prettier-eslint-cli` version: 4.7.1
- `prettier` version: 1.16.1
- `eslint` version: 5.3.0

Relevant code/config.
I have an invalid eslint rule, but pretter-eslint wasn't showing me this...
```
➤ npx prettier-eslint --write "*.js"
4 files were unchanged
➤ npx eslint *.js --fix
/my-project/.eslintrc.js:
        Configuration for rule "indent" is invalid:
        Severity should be one of the following: 0 = off, 1 = warn, 2 = error (you passed '4').

➤
```

What you did: ran --write *.js

What happened:
Was informed 4 files were unchanged... implying they are all good.

Reproduction:
in eslint config:
```
"rules": {
  "indent": 4
}
```

TODO... fork and create repro... :( https://github.com/kentcdodds/prettier-eslint-cli-repro

Problem description:
eslint was failing silently

Suggested solution:
Show eslint output!

**Comment by lpoulter** [comment]
It would be great to see eslint and prettier output for none writes also.
