### ISSUE TITLE
Add support for `--check`

### ISSUE THREAD

**Issue by OliverJAsh** [prettier/prettier-eslint-cli#147]
[prettier-cli recently added support for `--check`](https://prettier.io/docs/en/cli.html#check), which is similar to but different from `--list-different`.

Should prettier-eslint-cli propagate this option?

**Comment by zimme** [comment]
I'll merge a PR for this.

**Comment by OliverJAsh** [comment]
I'm trying to understand how I would implement this.

Looking at how `--list-different` works: https://github.com/prettier/prettier-eslint-cli/blob/4ef613e867713ffa37f7a9018f92131bdf0062e9/src/format-files.js#L259

IIUC, we would need a hook for when the process begins (to log "Checking formatting..."), and a hook for when the process ends along with the results (to log "Code style issues found in the above file(s). Forgot to run Prettier?" OR "All matched files use Prettier code style!"). How would I do that?

**Comment by matthew-dean** [comment]
I need the same for CI. Right now `prettier-eslint` pretends to succeed even if it didn't actually write any files vs. throwing an error on the command line if any file doesn't pass `prettier-eslint` settings.

**Comment by OliverJAsh** [comment]
This has quite a few up votes, can we reopen?
