### ISSUE TITLE
Output does not appear to be sent to eslint

### ISSUE THREAD

**Issue by tedconn** [prettier/prettier-eslint-cli#153]
- `prettier-eslint-cli` version: 4.7.1
- `prettier` version: I don't have prettier installed
- `eslint` version: 5.10.0

What you did:

running `yarn run eslint . --max-warnings 0` results in many warnings / errors
running `yarn run prettier-eslint --write` results in no changes

What happened:

Because the results of prettier are sent to eslint --fix I would have expected that there would be some changed files, since eslint is clearly saying that there are warnings and errors and prettier-eslint is just delegating to eslint after that. But it's not reporting anything...

**Comment by czebe** [comment]
We're also experiencing this issue. Prettier formats the files, but eslint errors never appear.

**Comment by tim-stasse** [comment]
I'm also experiencing this issue. Eslint reports errors, but prettier-eslint doesn't.

![image](https://user-images.githubusercontent.com/10667100/59317403-0c77aa80-8d06-11e9-8b8c-a3f930963ca0.png)

**Comment by zimme** [comment]
Try with version 5.0.0 of `prettier-eslint-cli` which uses version `9.0.0` of `prettier-eslint`.

**Comment by rapidfixer** [comment]
have the same issue with prettier-eslint 9.0.1. eslint isn't called
