### ISSUE TITLE
prettier-eslint-cli tries to format folder whos name ends with '.js'

### ISSUE THREAD

**Issue by nicu-chiciuc** [prettier/prettier-eslint-cli#167]
- `prettier-eslint-cli` version: 5.0.0
- `prettier` version: 1.18.2
- `eslint` version: 4.19.1

What you did:
Executed ```prettier-eslint --write \"server/**/*.js\" \"client/**/*.js\" \"tests/**/*.js\" \"imports/**/*.js\" ``` from a npm script

What happened:
Received the output:
```
prettier-eslint-cli [ERROR]: There was an error formatting "internal/path/to/folder/FinishSetup.js":
    Error: EISDIR: illegal operation on a directory, read
prettier-eslint-cli [ERROR]: There was an error formatting "internal/path/to/folder/TimeSlot.js":
    Error: EISDIR: illegal operation on a directory, read
success formatting 1 file with prettier-eslint
failure formatting 2 files with prettier-eslint
1520 files were unchanged
```

Problem description:
It seems that prettier-eslint-cli doesn't check whether it is trying to format a file or a folder and relies just on the name.

Suggested solution:
There should be a check in place so that even folders that are named `something.js` are viewed as folders.

**Comment by zimme** [comment]
Is this a problem when running just `eslint` or just `prettier`?

**Comment by nicu-chiciuc** [comment]
This is the exact script I'm using:
```
  "scripts": {
    "format-all-js": "prettier-eslint --write \"server/**/*.js\" \"client/**/*.js\" \"tests/**/*.js\" \"imports/**/*.js\" ",
...
// other scripts
```

I didn't get too much into it but I've checked where the error originates and it comes from [format-files.js#L280](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L280)

I thought maybe this is a known issue, otherwise I can get some time tonight and create an exact reproduction of the issue.

**Comment by zimme** [comment]
If you format the exact same files using just `prettier` and just `eslint` do you get the same error?

I just want to make sure this is an issue with `prettier-eslint-cli`/`prettier-eslint` and not a problem with `prettier` or `eslint`.

**Comment by nicu-chiciuc** [comment]
The problem is that it is not a file, it is a folder that is (unfortunately) named `FinishSetup.js`.

**Comment by zimme** [comment]
Yeah, I get that.

I still want to know if it's a problem when you run the formatting with just `prettier` and just `eslint` so I know if this is a problem with `prettier`, `eslint`, `prettier-eslint` or all of them.

**Comment by lifenstein** [comment]
I get the same issue. `prettier` and `eslint` don't crash, but `prettier-eslint` does.

**Comment by lifenstein** [comment]
I have minimally reproduced the error here: https://github.com/lifenstein/prettier-eslint-dir-issue-repro

We are actually getting another error when running the command on a much bigger `react` repo, but the reason seems to be the same, in that we were able to add the directory with the `.js` in the name to `.prettierignore` to stop the error.

This is what we get:
```
prettier-eslint-cli [ERROR]: There has been an unknown error when running the prettier-eslint CLI. If it's unclear to you what went wrong, then try this: 
  1. Run the script again with the LOG_LEVEL environment variable set to "trace"
  2. Search existing issues on GitHub: https://github.com/prettier/prettier-eslint-cli/issues?utf8=%E2%9C%93&q=%60string%60%20and%20%60indent%60%20should%20be%20strings
  3. Make a minimal reproduction in a totally separate repository. You can fork this one: https://github.com/kentcdodds/prettier-eslint-cli-repro
  4. Post an issue with a link to your reproduction to the issues on GitHub: https://github.com/prettier/prettier-eslint-cli/issues/new
/path/to/project/node_modules/prettier-eslint-cli/dist/uncaught-exception-handler.js:45
  throw err;
  ^

TypeError: `string` and `indent` should be strings
    at module.exports (/path/to/project/node_modules/indent-string/index.js:6:9)
    at SafeSubscriber.onError [as _error] (/path/to/project/node_modules/prettier-eslint-cli/dist/format-files.js:181:110)
    at SafeSubscriber.__tryOrUnsub (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:205:16)
    at SafeSubscriber.error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:156:26)
    at Subscriber._error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:92:26)
    at Subscriber.error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:72:18)
    at MergeMapSubscriber.OuterSubscriber.notifyError (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/OuterSubscriber.js:26:26)
    at InnerSubscriber._error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/InnerSubscriber.js:31:21)
    at InnerSubscriber.Subscriber.error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:72:18)
    at CatchSubscriber.Subscriber._error (/path/to/project/node_modules/prettier-eslint-cli/node_modules/rxjs/internal/Subscriber.js:92:26)
```

**Comment by zimme** [comment]
Ok, so it seems as though `prettier` and `eslint` on their own don't crash formatting folders with a `.js` in its name.

I'll mark this as a bug.

**Comment by egemon** [comment]
any updates?

**Comment by seyar-parleypro** [comment]
I have the same error. 
But then I pass full path 
```
 ./node_modules/.bin/prettier-eslint --write /Users/someuser/Projects/someproject/client/**/*.js
```
there are no errors

**Comment by seyar** [comment]
I had the same error.
But then I pass full path

` ./node_modules/.bin/prettier-eslint --write /Users/someuser/Projects/someproject/client/**/*.js`
there are no errors

**Comment by seyar** [comment]
I assume this is eslint error https://github.com/prettier/prettier-eslint-cli/issues/205
I downgraded eslint to 6.4.0 and this helped for me

**Comment by CoronaCoinCOVID** [comment]
Same error happens with *.test.js files, even when passing the file explicitly: `npx prettier-eslint test/foo.test.js`
As @seyar experienced, the bug goes away if the full path is used.
