### ISSUE TITLE
Relative paths are broken with eslint 6.7.0

### ISSUE THREAD

**Issue by brettjonesdev** [prettier/prettier-eslint-cli#205]
I recently upgrade my `eslint` and `prettier-eslint-cli` dependencies in a project, and ran into an error when running `prettier-eslint` command. 

I have created a [repository](https://github.com/brettjonesdev/prettier-eslint-dir-issue-repro) which reproduces the issue. 

There appears to be a bug within `prettier-eslint-cli` which breaks relative paths in file globs. Here's what I get when I run `prettier-eslint`:

```Terminal
> prettier-eslint './src/**/*.js' --list-different

prettier-eslint-cli [ERROR]: There was an error formatting "level1-dir/level2-dir2/test.js":
    Error: EISDIR: illegal operation on a directory, read
prettier-eslint [ERROR]: There was trouble creating the ESLint CLIEngine.
prettier-eslint-cli [ERROR]: There was an error formatting "level1-dir/level1-dir1/index.js":
    AssertionError [ERR_ASSERTION]: 'basePath' should be an absolute path.
        at new IgnorePattern (~/prettier-eslint-dir-issue-repro/node_modules/eslint/lib/cli-engine/config-array/ignore-pattern.js:178:9)
```

I tested, and it turns out that sure enough, if I replace `'./src/**/*.js` with an absolute path: `/Users/brett/projects/repo/src/**/*.js`, then `prettier-eslint` works as expected. 

Version:
```
"eslint": "6.7.0",
"eslint-plugin-import": "2.18.2",
"prettier-eslint-cli": "5.0.0",
```

**Comment by brettjonesdev** [comment]
A workaround I found is to just inject `pwd` output into the command in your `scripts`: 
`"test": "prettier-eslint \"$(pwd)/**/*.js\" --list-different"`

**Comment by weekitmo** [comment]
the same error，i replaced eslint version to 6.0.1 and the error disappears

**Comment by iGuan7u** [comment]
> \"$(pwd)/**/*.js\"

That saved my day. Thx!

**Comment by MrCheater** [comment]
+1

**Comment by ricahcyuzuzo** [comment]
Truly man This is Great!!

**Comment by gsonly** [comment]
I also experience this error with eslint 6.8.0, I think there is an issue with the latest version but roll back to version 6.0.1 worked fine.

**Comment by chrisbobbe** [comment]
Was this fixed in https://github.com/prettier/prettier-eslint-cli/pull/259? 🙂

**Comment by gsouf** [comment]
Short answer - no

**Comment by JounQin** [comment]
https://antfu.me/posts/why-reproductions-are-required

Feel free to create a new issue with minimal but runnable reproduction.

**Comment by gsouf** [comment]
@JounQin I think the ticket already describes the issue properly. Can't you reproduce it?

**Comment by JounQin** [comment]
> @JounQin I think the ticket already describes the issue properly. Can't you reproduce it?

This ticket is very old and outdated.

Perhaps https://github.com/prettier/prettier-eslint-cli/releases/tag/v5.0.1 has resolved this.

So if you still trouble with this, please feel free to create a new one instead.
