### ISSUE TITLE
Rules don't seem to get noticed

### ISSUE THREAD

**Issue by jdmwood** [prettier/prettier-eslint-cli#210]
- `prettier-eslint-cli` 5.0.0:
- `prettier` version: 1.19.1
- `eslint` version: 6.4.0

Relevant code/config.

`package.json`: 

```
{
  "name": "bug-test",
  "scripts": {
    "prettier": "prettier-eslint --write \"src/**/*.js\"",
    "eslint": "eslint \"src/**/*.js\""
  },
  "devDependencies": {
    "eslint": "6.4.0",
    "eslint-config-airbnb-base": "^14.0.0",
    "eslint-plugin-import": "^2.19.1",
    "prettier-eslint-cli": "^5.0.0"
  }
}
```

`.eslintrc`: 

```
{
  "extends": ["airbnb-base"]
}
```

`src/foo.js`:

```
const foo = 1;
```
See [bug.zip](https://github.com/prettier/prettier-eslint-cli/files/3969373/bug.zip) (include `package-lock`).

What you did:

```
npm install
npm run prettier
```

What happened:

I'd expect eslint to fail with a `no-unused-vars` error but instead it just silently passes:

```
$ npm run prettier

> bug-test@ prettier .../prettier-eslint-bug
> prettier-eslint --write "src/**/*.js"

1 file was unchanged
````

By way of comparison, if I run eslint directly, I do see the error:

```
$ npm run lint

> bug-test@ lint /.../prettier-eslint-bug
> eslint --fix "src/**/*.js"


.../src/foo.js
  1:7  error  'foo' is assigned a value but never used  no-unused-vars

✖ 1 problem (1 error, 0 warnings)
``` 

I have no idea if it's something special about this rule - this is just where we spotted the issue.

Reproduction:

See Zip above.

Problem description:

Suggested solution:

**Comment by pratyushj** [comment]
This is working as expected. 
Here is what happens in the code.
When you run `prettier-eslint-cli`, it essentially calls `prettier-eslint` passing the eslint configuration. 
Now [here](https://github.com/prettier/prettier-eslint/blob/4dfa4fbc615a6c6a4cd94e824421fdb2d80c4baf/src/utils.js#L77), some of the rules, which are not fixable through code ( You can find them in [eslint](https://github.com/eslint/eslint/tree/master/lib/rules), that for each rule there is a `fixable` key present or not ), get disabled, before passing the configuration to eslint. Thus, you are not able to see the eslint errors.  And I am assuming this is how authors have designed this tool.

**Comment by jdmwood2** [comment]
@pratyushj OK, interesting, thanks for your reply. I'm not sure why it's built this way. Seems a surprising behaviour and not what you'd expect or want.
