### ISSUE TITLE
Possible to override prettier options?

### ISSUE THREAD

**Issue by aaronjensen** [prettier/prettier-eslint-cli#26]
Unless I'm missing something, I'm not seeing a way to override prettier options w/ `prettier-eslint-cli`. It looks like it just uses `prettier-eslint`'s inference, which doesn't quite work in my situation. Is there a way at the moment? Thanks!

**Comment by kentcdodds** [comment]
Yeah, right now there's no way for you to configure `prettier` via `prettier-eslint-cli`. But that shouldn't be too complicated. I'm not sure how I want it done though. What kind of API would you expect for that?

**Comment by kentcdodds** [comment]
Note: most options for prettier are derived via the eslint config that's found for each file. But there are [a few `prettier` options](https://github.com/kentcdodds/prettier-eslint/blob/185378c1955a9b88e03aca830f59bcee35b1e0ca/src/utils.js#L109-L117) that we're not inferring yet (PRs welcome!).

**Comment by aaronjensen** [comment]
Ideally just accepting the same command line args that prettier accepts would be fine until they have a json config.

**Comment by kentcdodds** [comment]
Ok, I'm a tiny bit worried about this because if you have prettier configured in one way and eslint configured in another way, eslint will ultimately win. What if we only expose flags for the things which we cannot yet infer?

**Comment by aaronjensen** [comment]
I'm fine w/ that. My problem at the moment is with `trailingComma` which is going to change in prettier 0.19.0 (and allow your inference to be more discerning).

Perhaps it'd be better to spend time adding inference for the other options. Are there any that are not actually inferrable?

**Comment by kentcdodds** [comment]
Not that I'm aware of. I'm pretty sure they're all inferrable. But thinking about it now I could see a situation where someone could disable stylistic rules in eslint and configure prettier instead. So we should probably just include them all. Then we could add a warning in `prettier-eslint` for when there's a conflict just so users know and can fix it.

**Comment by kentcdodds** [comment]
I'm pretty sure this is now supported 👍
