### ISSUE TITLE
Stop using ESLint 5's `ConfigFile.load`, which is gone in ESLint 6.

### ISSUE THREAD

**Issue by chrisbobbe** [prettier/prettier-eslint-cli#303]
`prettier-eslint-cli` can't currently use ESLint 6, and it would be great to fix that (see #304).

Ever since #91 was merged, `pretter-eslint-cli` has been using a util function `ConfigFile.load` that doesn't exist in ESLint 6; it was removed in https://github.com/eslint/eslint/pull/11546 (merged in https://github.com/eslint/eslint/commit/6ae21a4bfe5a1566f787fbad798182a524b96d28; released in [v6.0.0-alpha.1](https://github.com/eslint/eslint/releases/tag/v6.0.0-alpha.1)).

To see the problem in action, get `prettier-eslint-cli` to use ESLint 6 (e.g., 6.8.0). One way to do this is to put lines like the following in the `package.json` of a project that uses `prettier-eslint-cli`:

```diff
+  "resolutions": {
+    "prettier-eslint-cli/eslint": "^6.8.0",
+    "prettier-eslint-cli/prettier-eslint": "^11.0.0"
+  }
```

Run `yarn`/`npm install`, then run the CLI, and see error output containing this:

```
Error: Cannot find module 'eslint/lib/config/config-file'
```

If it's important that we keep invoking ESLint's code for loading an ESLint config, it would be great to try to use something that's unambiguously part of ESLint's public API.

If it's not important, it might be good to stop doing so. In particular, I think the current behavior doesn't align with [this bit of basic summary in the README](https://github.com/prettier/prettier-eslint-cli/blob/v5.0.0/README.md#this-solution) for what `prettier-eslint-cli` does:

> `prettier-eslint-cli` forwards on the `filePath` and other relevant options to `prettier-eslint` which identifies the applicable `ESLint` config for each file and uses that to determine the options for `prettier` and `eslint --fix`.

**Comment by chrisbobbe** [comment]
Go away stale-bot, there’s no sign this issue has been fixed. 🙂

**Comment by chrisbobbe** [comment]
Still no sign this issue has been fixed.

**Comment by aronwoost** [comment]
It is not. 😕
