### ISSUE TITLE
Support `prettier-eslint`, `prettier`, and `eslint` later than v9.0.2, v1.19.1, and v5.16.0.

### ISSUE THREAD

**Issue by chrisbobbe** [prettier/prettier-eslint-cli#304]
`prettier-eslint-cli` at its latest is pulling in and using versions of `prettier-eslint`, `eslint`, and `prettier` that are getting a bit old; in particular, ESLint 6 has been out for a while now, and it would be great to be able to use it (or even ESLint 7). Here are the latest of those packages that are currently supported at `prettier-eslint-cli` v5.0.1 (the current latest):

- [ ] `prettier-eslint` v9.0.2 ([^9.0.0 is the range `prettier-eslint-cli` v5.0.1 depends on](https://github.com/prettier/prettier-eslint-cli/blob/v5.0.1/package.json#L41))
- [ ] `prettier` v1.19.1 ([^1.7.0 is the range `prettier-eslint` v9.0.2 depends on](https://github.com/prettier/prettier-eslint/blob/v9.0.2/package.json#L29))
- [ ] `eslint` v5.16.0 (^5.0.0 is [the range `prettier-eslint-cli` v5.0.1 depends on](https://github.com/prettier/prettier-eslint-cli/blob/v5.0.1/package.json#L33) and [the range `prettier-eslint` v9.0.2 depends on](https://github.com/prettier/prettier-eslint/blob/v9.0.2/package.json#L25))

Supporting ESLint 6 is currently blocked by https://github.com/prettier/prettier-eslint-cli/issues/303.

**Comment by gaving** [comment]
Really interested in this one, in an annoying place at the moment where my project is on eslint 7 / prettier 2 but my preferred editor (neovim lsp) is using prettier-eslint-cli which seems to have quite a few indentation differences.

**Comment by chrisbobbe** [comment]
Go away stale-bot, there's no sign this issue has been fixed. :)

**Comment by AdnanTheExcellent** [comment]
this would be great. this package is cluttering up my yarn.lock file with old dependencies.

**Comment by chrisbobbe** [comment]
(The issue hasn't been fixed.)

**Comment by aronwoost** [comment]
This issue is not fixed.

**Comment by chrisbobbe** [comment]
@prettier, would you please consider reopening this and https://github.com/prettier/prettier-eslint-cli/issues/303? 🙂 I think it wasn't intended that the stale-bot would close them; please see 5ebffc9cc where the stale-bot was turned off. Thank you!

**Comment by azatoth** [comment]
@kylemh I think this issue should be reopened.

**Comment by kylemh** [comment]
Agreed!

**Comment by idahogurl** [comment]
Closed by #431
