### ISSUE TITLE
add ability to run for a single file?

### ISSUE THREAD

**Issue by chrisdrackett** [prettier/prettier-eslint-cli#34]
this would let you use this in a flow like https://github.com/prettier/prettier#pre-commit-hook-for-changed-files just like the base prettier cli

**Comment by kentcdodds** [comment]
This totally works :) https://github.com/kentcdodds/nps/blob/master/package.json#L76-L81

**Comment by chrisdrackett** [comment]
it does, hence me closing my ticket in disgrace.

**Comment by kentcdodds** [comment]
lol, no worries :)
