### ISSUE TITLE
Success and error messages are printed to stdout when reading from a file

### ISSUE THREAD

**Issue by osener** [prettier/prettier-eslint-cli#36]
This makes it hard to use this tool as a drop-in replacement for prettier, for example when using Emacs editor integration https://github.com/prettier/prettier/tree/master/editors/emacs as it works using temporary files instead of `--stdin`.

I was able to fix this easily by using `console.error` instead of `console.log` in `format-files.js`, but couldn't send a quick PR as it breaks more than half of the tests.

```sh
$ echo "import      'foo'" > file.js
$ prettier-eslint file.js > formatted.js
```

formatted.js contents:
```
import 'foo'

success formatting 1 file with prettier-eslint
```

**Comment by kentcdodds** [comment]
Ok, what if we add a flag called `--summary-log` which defaulted to `true` and you could disable it with `--no-summary-log`? The way this would work with `yargs` is you'd simply add `'summary-log'` to the options in [the parser](https://github.com/prettier/prettier-eslint-cli/blob/master/src/parser.js). It would be really similar to [`eslint-ignore`](https://github.com/prettier/prettier-eslint-cli/blob/master/src/parser.js#L19-L27).

Then in [format-files.js](https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js) we could accept `summaryLog` and only log the info messages if `summaryLog` is true.

How does that sound? Feel free to [makeapullrequest.com](http://makeapullrequest.com) :)

**Comment by osener** [comment]
I was actually expecting `prettier-eslint -l silent` to work the way you described. It could be useful to utilize logging level or add a new flag for controlling whether to print this info, but I think these types of messages belong to [`stderr`](http://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout) nevertheless.

I'll definitely create a PR if I find the time. Thanks for the quick response!

**Comment by kentcdodds** [comment]
> I think these types of messages belong to stderr nevertheless.

How so? It seems odd to me to put this in stderr:

```
success formatting 1 file with prettier-eslint
```

**Comment by osener** [comment]
Stderr is not only for errors, but also for diagnostic messages. Outputting the data in stdout and printing the meta messages on stderr allows users to consume the formatted JS by reading stdout. Simplest example of this is `prettier-eslint file.js > formatted.js`.

This is outlined in POSIX standard as explained here: https://unix.stackexchange.com/questions/331611/do-progress-reports-logging-information-belong-on-stderr-or-stdout. The third answer also makes a good point that no diagnostic information should be outputted in case of successful execution, so I think even if `--summary-log` is added, it should default to false.

**Comment by denis-sokolov** [comment]
I was very surprised when I saw the `success` message in the `stdout`. What is the purpose of outputting the cleaned file to `stdout` if I can’t use the output, since it’s inclusive of diagnostic messages? I would be happy to see that switched to `stderr`!

**Comment by kentcdodds** [comment]
Happy to accept a pull request to improve this. Thanks!

**Comment by kentcdodds** [comment]
This has been released in the latest version :)
