### ISSUE TITLE
Feature request: Allow specifying eslint configuration file as an argument

### ISSUE THREAD

**Issue by osener** [prettier/prettier-eslint-cli#37]
This would make it easier to use prettier-eslint as a drop-in replacement for prettier by removing the requirement for `.eslint` file to be in the working directory.

Also affects [Emacs integration](https://github.com/prettier/prettier/tree/master/editors/emacs) because it calls prettier on a copy of the file under the temp directory of the OS (such as `/var/folders/...`, or `/tmp`)

**Comment by kentcdodds** [comment]
Hey @osener, I've definitely [considered this](https://github.com/prettier/prettier-eslint-cli/blob/455668d4520ffe71646f58b754ddf1333f4576ce/src/parser.js#L52-L59) and would love help doing it! Would you like to give it a go? There may be some utilities in the eslint package that we could use to read the file by the path.

**Comment by haasDev** [comment]
@osener have you started working on this at all?  This is something we definitely want as a feature as well.

**Comment by osener** [comment]
@haasDev unfortunately I don't expect to have time for this in the coming weeks

**Comment by slightlytyler** [comment]
I'm confused on what the current behavior is? I can't get this package to recognize my eslint conifg at all, even when it's in the working directory

**Comment by kentcdodds** [comment]
Hmmm... Could you follow the debugging instructions in the README too figure out what's going on?

**Comment by slightlytyler** [comment]
@kentcdodds nvm got it working, not sure what I did wrong first try lol. Would still love this feature as I'm currently re-exporting my eslint config at the root

**Comment by kentcdodds** [comment]
Yeah, agreed. Would you like to [work on it](http://makeapullrequest.com/)?

Curious why you have your config in a different file at all if you're already re-exporting it at the root... 🤔

**Comment by eqyiel** [comment]
@osener I was looking at doing something like this:

https://github.com/eqyiel/prettier-eslint-cli/commit/8834165ae5bcfafebb5236c776eabd6a036caa54
https://github.com/eqyiel/prettier-eslint/commit/73f84e9b70e00780421362459842e9f9e20f4d14

I found that [I didn't want to manually specify the config path](https://github.com/eqyiel/prettier-eslint-cli/issues/1), but wanted `prettier-eslint` to figure it out for me automagically like it does this if you give it the `filePath` prop: https://github.com/prettier/prettier-eslint/blob/bee9283f005fda2b08d1940f4455169333effa07/src/index.js#L201-L226

So my workaround currently is to call `prettier-eslint-cli` like this:

```
$ prettier-eslint --stdin app/containers/Fundraise.js < app/containers/Fundraise.js
```

This way it picks up the `eslint` configuration correctly (from the `filePath`) but only operates on the file piped into stdin.

It also doesn't write to `filePath` without the `--write` flag, so this works for the Emacs integration.  I'll send a PR there shortly.
