### ISSUE TITLE
Have the equivalent of prettier -l option

### ISSUE THREAD

**Issue by kennydee** [prettier/prettier-eslint-cli#38]
Hi,
First, thanks for your work, this is very usefull !

Is there anyway to have a `-l` option equivalent to the one from prettier to know what are the file that are not `prettier-eslint` yet ? 

See the PR from the `prettier` repos adding this option : https://github.com/prettier/prettier/pull/854

It could be usefull to be able to launch `prettier-eslint -l "src/**/*.js` to check on CI if all the files have passed the `prettier-eslint` script.

P.S: we can't use the `-l` from prettier here because it doesn't rely on Eslint config.

Thanks

Kenny

**Comment by kentcdodds** [comment]
Sure, I'd be fine to accept a PR that does this. We can't use `-l` though because that's an alias to `--log-level` so we'd need to come up with something else. Feel free to [makeapullrequest.com](http://makeapullrequest.com) :)

**Comment by kennydee** [comment]
Ok will see :)

For now, i have found a workaround to achieve the same goals : 
I've added `eslint-plugin-prettier` to my project, so lint (and CI) will failed if files are not `prettier` formated.

Will see if this is enough, or if a check option for prettier-eslint is always needed.

Thanks for your feedback.
Feel free to close if you think so.

**Comment by kentcdodds** [comment]
I'll go ahead and close, but anyone can feel free to bring this up again. I'd be happy to accept a PR for it.
