### ISSUE TITLE
I have problem about this package,

### ISSUE THREAD

**Issue by lockunlatui** [prettier/prettier-eslint-cli#392]
- `prettier-eslint-cli` version:
- `prettier` version:
- `eslint` version:

Relevant code/config.

```javascript

```

What you did:

What happened:

Reproduction:

-- paste your link here --

Problem description:

Suggested solution:

**Comment by chrisbobbe** [comment]
This issue is totally blank except for what looks like a new-issue template. Would you please close it or provide a detailed description of the problem (including, if you can, a minimal reproduction recipe for the bug, if it is a bug)? 🙂
