### ISSUE TITLE
What different beween use prettier-eslint-cli and use  prettier and eslint step by step?

### ISSUE THREAD

**Issue by thanhkaiba** [prettier/prettier-eslint-cli#398]
I use prettier-eslint-cli for my project. I wonder should I just use prettier -- write and eslint --fix instead use this prettier-eslint-cl?

**Comment by davidmondok** [comment]
I'm wondering about this too

**Comment by idahogurl** [comment]
The difference is explained in the Prettier-ESLint README here https://github.com/prettier/prettier-eslint#the-problem. Essentially ESLint and Prettier can have conflicting settings and `prettier-eslint` attempts to resolve those differences by looking at both your Prettier and ESLint configurations and making a single rule set.
