### ISSUE TITLE
Can an error be reported when the error cannot be resolved?

### ISSUE THREAD

**Issue by qieqie7** [prettier/prettier-eslint-cli#411]
- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: 2.3.0
- `eslint` version: 7.26.0

Relevant code/config.

```javascript
const a = 'longlonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglonglong';
```

What you did:
package.json
```json
{
  "husky": {
        "hooks": {
            "pre-commit": "lint-staged"
        }
    },
    "lint-staged": {
        "src/**/*.{js,jsx,ts,tsx}": [
            "prettier-eslint --write"
        ]
    }
|
```

What happened:
start,
![image](https://user-images.githubusercontent.com/30360513/122384806-a2520a00-cf9e-11eb-91eb-6f9669c96dab.png)

then I will git commit this change

![image](https://user-images.githubusercontent.com/30360513/122384932-c7467d00-cf9e-11eb-9876-d0504f032596.png)

Reproduction:

-- paste your link here --

Problem description:

But the error is not resolved

Suggested solution:

I hope this change can't commit. And throw this error.

**Comment by JounQin** [comment]
https://antfu.me/posts/why-reproductions-are-required

Feel free to create a new issue with minimal but runnable reproduction.
