### ISSUE TITLE
`--list-different` doesn't exclude node_modules

### ISSUE THREAD

**Issue by runely** [prettier/prettier-eslint-cli#420]
- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: 2.3.2
- `eslint` version: 7.30.0

Relevant code/config.

```javascript
extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 6
  },
  env: {
    node: true
  },
  settings: {
    jest: {
      version: 26
    }
  },
  rules: {
    quotes: [
      'error',
      'single',
      {
        avoidEscape: true
      }
    ],
    semi: [
      2,
      'never'
    ]
  }
```

What you did:
npx prettier-eslint --list-different **/*.js

What happened:
JavaScript files from node_modules are listed.

![image](https://user-images.githubusercontent.com/25814673/125188599-97ecfe00-e234-11eb-9286-5fe3a89da65c.png)

Problem description:
`--list-different` should by default have excluded node_modules directory

**Comment by JounQin** [comment]
`**/*.js` will of course match `node_modules`
