### ISSUE TITLE
`--list-different` from script fails

### ISSUE THREAD

**Issue by runely** [prettier/prettier-eslint-cli#421]
- `prettier-eslint-cli` version: 5.0.1
- `prettier` version: 2.3.2
- `eslint` version: 7.30.0

Relevant code/config.

```javascript
extends: ['eslint:recommended'],
  parserOptions: {
    ecmaVersion: 6
  },
  env: {
    node: true
  },
  settings: {
    jest: {
      version: 26
    }
  },
  rules: {
    quotes: [
      'error',
      'single',
      {
        avoidEscape: true
      }
    ],
    semi: [
      2,
      'never'
    ]
  }
```

**npm script**
```javascript
"scripts": {
    "lint": "prettier-eslint --list-different **/*.js"
  }
```

What you did:
npm run lint

What happened:
Fails with error `Cannot read property 'match' of undefined`

![image](https://user-images.githubusercontent.com/25814673/125188885-c8816780-e235-11eb-8f54-b11677787aea.png)

Problem description:
`prettier-eslint --list-different` fails with error `Cannot read property 'match' of undefined`

**Comment by JounQin** [comment]
PR welcome to fix this issue.

And also please read https://antfu.me/posts/why-reproductions-are-required
