### ISSUE TITLE
Doesn't save fixes

### ISSUE THREAD

**Issue by MoeSattler** [prettier/prettier-eslint-cli#43]
When running `prettier-eslint "src/**/*.js"` it displays the correct changes in the cli but does not save them. I get no error message.

**Comment by sdeleon28** [comment]
I have this problem as well. How did you get it fixed?

**Comment by kentcdodds** [comment]
Make sure that you add the flag `--write`

**Comment by sdeleon28** [comment]
Yeah, I saw that in the README after I posted the comment. Thank you!
