### ISSUE TITLE
eslint-ignore does not respect deeply nested node_modules folders

### ISSUE THREAD

**Issue by KevinGrandon** [prettier/prettier-eslint-cli#44]
Given a directory structure like:
```
/
/node_modules/
/subfolder/node_modules/
```

And a .eslintignore like:
```
**/node_modules/**
```

Running prettier will attempt to format code within subfolder/node_modules. It's expected that it would not format this directory since eslint ignores it.

**Comment by kentcdodds** [comment]
Hmmmmm.... Could you make a small repo the reproduce the issue? What do you propose for a solution? Would you like to http://makeapullrequest.com?

**Comment by kentcdodds** [comment]
I'm going to go ahead and mark this one as closed. Please reopen with a reproduction repository if it's still a problem. Thanks!
