### ISSUE TITLE
Feature request: allow prettier options such as "--trailing-comma"

### ISSUE THREAD

**Issue by Gandem** [prettier/prettier-eslint-cli#45]
Hello !

First of all, I am actually using prettier-eslint with Neoformat in Vim, and it's awesome, thank you so much for these projects 😄 

One problem I encountered is while using the cli in a small NodeJS project (that has no babel pipeline). The problem is that prettier add comma dangles in function arguments by default, and the latest version of Node does not yet support this feature. Prettier has a flag already implemented for that use case, which is "`--trailing-commas es5`".

I saw that there was a todo [here](https://github.com/prettier/prettier-eslint-cli/blob/455668d4520ffe71646f58b754ddf1333f4576ce/src/parser.js#L60-L65) that considered using "some" prettier configuration in prettier-eslint-cli.

One idea would be passing the flags prefixed : `--prettier-trailing-commas es5` !

How do you think this should be done ? I would be glad to try to work on it, if possible :) 

Edit: I saw that https://github.com/prettier/prettier-eslint-cli/issues/26 aborded the same subject, but the issue is more focused on the inference between eslint and prettier. I don't know if it would best to talk about the issue there. If so, let me know, I would be glad to close this issue 😃

**Comment by kentcdodds** [comment]
Hi @Gandem! I'm glad the project's been helpful to you! Feel free to [makeapullrequest.com](http://makeapullrequest.com)! I like your idea of prefixing the flags. We could support all the prettier flags that way with very little trouble. Feel free to experiment and let me know if you need a hand :hand:

Thanks!

**Comment by cef62** [comment]
This is a great addition! Anyway I run in an error for boolean values. I want set `semi` option to false.
I've tried passing it as `--prettier.semi false` and `--prettier.semi 0`, in both situations I get the following error:

```shell
prettier-eslint [ERROR]: prettier formatting failed due to a prettier error
prettier-eslint-cli [ERROR]: There was an error formatting "src/utils.js":
    ● Validation Error:

      Option "semi" must be of type:
        boolean
      but instead received:
        number

      Example:
      {
        "semi": true
      }
```
Do you have any hin? Otherwise I'll try to make a PR to resolve the issue

**Comment by Gandem** [comment]
Oh, I guess yargs dot-notation gets the string value by default so `--prettier.semi false` is being interpreted as :
```
{
    "semi": "false"
} 
```

For truthy values, that's not a problem as `--prettier.semi` is interpreted as :
```
{
    "semi": true
} 
```

I have an idea to fix this problem ! I'll make a PR soon 😃

**Comment by cef62** [comment]
I went ahed and submitted #47, let me know if is enough for you.
