### ISSUE TITLE
Trailing empty line problem

### ISSUE THREAD

**Issue by coldfish** [prettier/prettier-eslint-cli#51]
I'm using prettier-eslint-cli for vim and prettier-eslint for Atom right now. Everything works great and they gave me the same results except a tiny problem.

After formatting the code via Vim using this configuration:

`autocmd FileType javascript.jsx,javascript setlocal formatprg=prettier-eslint\ --stdin\ --prettier.jsx-bracket-same-line\ --prettier.parser\ babylon\ --prettier.single-quote\ --prettier.trailing-comma\ none`

prettier-eslint-cli formatter is adding a new empty line to the EOF.

Missing something on the tool configuration side?

**Comment by kentcdodds** [comment]
Hmmm... That's odd. I'm not sure. Really depends on a lot of stuff. Could you dig a little deeper? You might find the `--log-level` option useful. In Atom, you can [open dev tools](https://discuss.atom.io/t/how-to-make-developer-tools-appear/16232) and type: `process.env.LOG_LEVEL = 'trace'` and you'll get helpful logs there too.

Happy to review [PRs](http://makeapullrequest.com)!

**Comment by coldfish** [comment]
Unfortunately, there's no clear distinction between the traces got from the both side(Atom and vim).

On the vim side, if I run prettier and eslint independently, there's no problem on the output. 

As a workaround, I had to add **noeol** and **binary** option to my vim configuration:

`autocmd FileType javascript.jsx,javascript setlocal noeol binary formatprg=prettier-eslint\ --stdin\ --prettier.jsx-bracket-same-line\ --prettier.parser\ babylon\ --prettier.single-quote\ --prettier.trailing-comma\ all`

Thanks for your help.

**Comment by kentcdodds** [comment]
Huh, yeah, I'm not sure what's causing the issue, but I'm glad you got a workaround that works. Based on your workaround I expect that this is unrelated to prettier-eslint. Thanks!

**Comment by zenbo** [comment]
Don't print double newlines at EOF to stdout by lydell · Pull Request #437 · prettier/prettier
https://github.com/prettier/prettier/pull/437

**Comment by kentcdodds** [comment]
Ah! That makes sense! Anyone want to make a pull request for that?
