### ISSUE TITLE
Requires Node 4, should have engines listed in package.json

### ISSUE THREAD

**Issue by MikeyBurkman** [prettier/prettier-eslint-cli#52]
I tried installing this in one of our legacy projects, but had a runtime error because there are string templates in the code, and we're still stuck on node 0.12. (Yeah I know, it's ancient.) 

The package.json file should probably have `engines` added to it, so it's enforced that it can't be installed on older node versions.

**Comment by kentcdodds** [comment]
Good point! Would you mind making a PR for that?
