### ISSUE TITLE
Add more logging

### ISSUE THREAD

**Issue by kentcdodds** [prettier/prettier-eslint-cli#55]
@xjamundx ran into an issue where the `prettier` module couldn't be found [here](https://github.com/prettier/prettier-eslint-cli/blob/90295930867a77fe52dd86a80f8741b815d42838/src/parser.js#L92) and the error was cryptic. Having better logging would be nice.

**Comment by xjamundx** [comment]
Specifically if prettier is missing you get a super weird error message and `--log-level` doesn't do anything. Should be easy enough to change the error message to something like "Could not find required dependency: prettier`
