### ISSUE TITLE
Doesn't recognize single-quote option of prettier

### ISSUE THREAD

**Issue by diondirza** [prettier/prettier-eslint-cli#60]
- `prettier-eslint-cli` version: 4.0.0
- `prettier` version: 1.3.1
- `eslint` version: 3.19.0

With the last version, I tried to use this command 
`prettier-eslint --print-width 100 --single-quote --trailing-comma all --write`

and it showed an error `Unknown argument: single-quote'. Does this option being replaced by another option?

**Comment by kentcdodds** [comment]
Sorry about that. We missed it! A new release should be out momentarily :+1:

**Comment by kentcdodds** [comment]
Thanks for reporting the bug. Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

**Comment by diondirza** [comment]
Sure if you don't mind 😁

**Comment by kentcdodds** [comment]
Yes please! Bug reports are helpful contributions!
