### ISSUE TITLE
Breaking change in 3.4.2: trailing comma from prettier-eslint 6.0.0

### ISSUE THREAD

**Issue by denis-sokolov** [prettier/prettier-eslint-cli#64]
In c5e802ef0, this project has upgraded its dependency `prettier-eslint` to 6.0.0. This introduced a backwards-compatibility breaking change, as `prettier-eslint` [starting from 6.0.0](https://github.com/prettier/prettier-eslint/releases/tag/v6.0.0) has a different default for trailing commas. Unlike `prettier-eslint`, however, this project released this change as a patch version 3.4.2. In our codebase, running `prettier-eslint-cli@3.4.2` now generates a huge diff because it removes all trailing commas.

Seeing how there’s version 4.0.0 of `prettier-eslint-cli` that is cheerily moving forward, I would suggest releasing another version in the 3.x branch that reverts the breaking change only to maintain stability for users who have not upgraded yet.

#62 seems tangentially related.

**Comment by kentcdodds** [comment]
Makes sense :+1: sorry about that. I'll be more careful about those kinds of changes in the future. Thanks!

**Comment by kentcdodds** [comment]
This has been published as 3.6.1

**Comment by denis-sokolov** [comment]
Thanks for a quick response and a release. While I can confirm the main issue gone, there are still a few minor formatting differences between 3.4.1 and 3.6.1, but at least it’s not replacing the entire project.

**Comment by kentcdodds** [comment]
Yeah, sorry about that. Hopefully this wont be an issue in the future.

**Comment by lukaszmoroz** [comment]
3.6.1 is now tagged `latest` on npm, so you may want to update it.

**Comment by kentcdodds** [comment]
Whoops! Thanks for that! Updating now :+1:
