### ISSUE TITLE
obsolete docs concerning --prettier option

### ISSUE THREAD

**Issue by marzelin** [prettier/prettier-eslint-cli#67]
In #59 a breaking change was introduced that removed `--prettier` option in favor of directly passing options to prettier.

Unfortunately, docs weren't updated to reflect changes in code.

What is even worse, this breaking change was first pushed as a minor patch `3.6.1` which puts people using 3.X.X version and `--prettier` option in a pretty bad situation.

Also 3.6.1 is the latest of 36 releases at https://www.npmjs.com/package/prettier-eslint-cli

**Comment by kentcdodds** [comment]
> Also 3.6.1 is the latest of 36 releases at https://www.npmjs.com/package/prettier-eslint-cli

Fixed that

> What is even worse, this breaking change was first pushed as a minor patch 3.6.1 which puts people using 3.X.X version and --prettier option in a pretty bad situation.

That was my mistake when I tried to address #64 :-(

At this point I'm going to just say that `3.x` is deprecated (will deprecate in a moment) and ask that people upgrade to 4.x. Sorry about all of that!
