### ISSUE TITLE
Unexpected changes to formatted result after bumping to v4

### ISSUE THREAD

**Issue by robwise** [prettier/prettier-eslint-cli#71]
- `prettier-eslint-cli` version: 4.0.3
- `prettier` version: 1.4.2
- `eslint` version: 3.19.0

Relevant code/config.

```javascript
// before
type foo = 'hello world';
type bar = { baz: null };

// after
type foo = "hello world";
type bar = {baz: null};
```

What you did: I bumped from 3.6.0 to 4.0.3 and ran the formatter. Reverting to 3.6.0 solves all of the below problems.

What happened: 
- Flow annotations' quotations changed to double quotes
- Flow annotations lost bracket spacing
- Many instances of going over max line length when it didn't before. These cases aren't the usual instance where prettier formats it in a way that is below line length but then eslint fixes it in a way that is longer, these are cases where prettier should have wrapped itself before it even got to the eslint step.

I can't be sure, but it seems as though the prettier eslint inference isn't working right or something? And eslint --fix is covering it up (except for these issues)?

**Comment by kentcdodds** [comment]
I wonder whether this is related to the [`v6.2.1`](https://github.com/prettier/prettier-eslint/releases/tag/v6.2.1) release of `prettier-eslint` which was _supposed_ to be non-breaking, but probably wasn't 🤔

**Comment by mrm007** [comment]
[I got you](https://github.com/prettier/prettier-eslint-cli/pull/72).

**Comment by kentcdodds** [comment]
Merged! Thanks!
