### ISSUE TITLE
Success format messages don't respect logLevel

### ISSUE THREAD

**Issue by jackfranklin** [prettier/prettier-eslint-cli#73]
I just noticed that the logging for the success/failure message (https://github.com/prettier/prettier-eslint-cli/blob/master/src/format-files.js#L128) doesn't respect the log level. I'd expect if I set `--log-level silent` that I would see literally no logging. 

The reason I ask about this is because I'm writing a script to check Prettier against any JS files in `git diff` and the output right now looks a bit weird because `prettier-eslint` formats `foo.js` and outputs 'success formatting foo.js' but the actual script fails because the formatted `foo.js` doesn't match `foo.js` on disk.

Would you be open to a PR that made the logging above respect `logLevel` and just use `log.info` instead?

**Comment by kentcdodds** [comment]
Hmmmmm. I think that'd be fine. But I seem to remember someone having an issue with us using anything but stderr for logging off that nature. Maybe @osener and @denis-sokolov could share their thoughts.

**Comment by denis-sokolov** [comment]
Indeed we don’t respect the log-level and we should.

I don’t believe we respected it before 81f6542b22 either. We switched from `console.log` to `console.error`, we did not touch the `logger` that was added in #31.

@jackfranklin, for your needs you should do unix pipe redirection anyway: `eslint-prettier-cli 2>/dev/null` will hide diagnostic messages. Why bother with log level?

**Comment by jackfranklin** [comment]
@denis-sokolov that's fair, I didn't think of doing that. However I do think I should be able to achieve the same by setting log level to silent - to me that's more intuitive. I am happy to take a stab at the PR if you'd like, else feel free to go ahead and close :)

Thanks for all your work on this tool btw 🎉

**Comment by kentcdodds** [comment]
Thanks @denis-sokolov! Yeah, let's get a PR merged that not only preserves the `stderr` behavior but also honors the `log-level`. Probably wont be able to use `logger` because it uses `stdout` for everything except `error` which wouldn't make sense to me. I think most folks like to see it by default, so what do you think we log it unless the log level is set to silent?

**Comment by jackfranklin** [comment]
Agree - so shall I leave the calls using `console.error` but wrap them in an `if (logLevel is silent)` type thing?

**Comment by kentcdodds** [comment]
That sounds perfect 👍

**Comment by jackfranklin** [comment]
PS: I still find it kinda weird that the success case still uses console.error but I'm willing to go with that ;)

**Comment by denis-sokolov** [comment]
@jackfranklin, if you find `console.error`, consider that it’s just a shorthand. From inside the Node program we can directly write to any of the standard outputs with `process.stdout.write` and `process.stderr.write`.

**Comment by jackfranklin** [comment]
@denis-sokolov I meant more in that I find it odd that there's a success message, and you use `console.error` to log it. I can understand why but it's a bit jarring on first glance! I'll get a PR in soon :)

**Comment by kentcdodds** [comment]
It is a bit jarring, maybe as part of your PR you could add a short comment explaining why.
