### ISSUE TITLE
Exit(1) with --list-different

### ISSUE THREAD

**Issue by moretti** [prettier/prettier-eslint-cli#77]
From the prettier docs:
>`prettier` with `--list-different` prints the filenames of files that are different from prettier formatting.
> If there are differences the script errors out, which is useful in a CI scenario:

```
prettier --list-different '**/*.js'
file.js
error Command failed with exit code 1.
```

Unfortunately this doesn't seem to work with `prettier-eslint`:
```
prettier-eslint --list-different '**/*.js'
file.js
success formatting 1 file with prettier-eslint
```
(The exit code in this case is 0, should be > 0)

I'm happy to submit a PR if you think we should fix it.

---

- `prettier-eslint-cli` version: 4.1.0
- `prettier` version: 1.4.4
- `eslint` version: 3.19.0

**Comment by kentcdodds** [comment]
Yep. I'd like this CLI to match the original `prettier` CLI as much as possible :+1: Thanks in advance for the PR!
