### ISSUE TITLE
Alignment with the eslint cli

### ISSUE THREAD

**Issue by BarryThePenguin** [prettier/prettier-eslint-cli#79]
- `prettier-eslint-cli` version: 4.1.1
- `prettier` version: 1.4.4
- `eslint` version: 3.19.0

What you did:

Replaced `eslint` with `prettier-eslint-cli`

What happened:

```shell
$ prettier-eslint-cli .
prettier-eslint-cli [ERROR]: There was an error formatting ".": 
    Error: EISDIR: illegal operation on a directory, read
failure formatting 1 file with prettier-eslint
```

Received the same output for
```shell
$ prettier-eslint-cli test
```

Running with a glob only changed one file, not the two files in my project (index.js and test/index.js)
```shell
$ prettier-eslint-cli **/*.js
1 file was changed
```

Problem description:

Coming from `eslint` I was hoping that `prettier-eslint-cli` would be a drop in replacement. A lot of the projects I work on run `eslint` on the src and test directories while using [`--ignore-path .gitignore`](http://eslint.org/docs/user-guide/command-line-interface#--ignore-path). Other projects use `eslint` with `.`, allowing eslint to use the default [`--ext .js`](http://eslint.org/docs/user-guide/command-line-interface#--ext) option.

Suggested solution:

I'm not sure which package this request falls into (`prettier-eslint-cli` or `prettier-eslint`), but it would be great if the cli options were closer to that of `eslint` cli.

**Comment by kentcdodds** [comment]
Hi @BarryThePenguin :wave:

I see `prettier-eslint` as more of a replacement for `prettier` than a replacement for `eslint`. So I'm more interested in mimicking the `prettier` CLI than the `eslint` CLI. Also, `eslint` does a lot of wacky things to make the CLI the way it is and I'd prefer to not add that complexity to this tool. I think it works well as it is and I'm not really interested in adding a lot of complexity to it. Sorry.
