### ISSUE TITLE
Feature request: add option "--space-function-paren"

### ISSUE THREAD

**Issue by bySabi** [prettier/prettier-eslint-cli#81]
Hi.

I'm using both tools [semistandard](https://github.com/Flet/semistandard) and `prettier-eslint-cli` but they disagree on `space-before-function-paren`  rule.
Here will be useful to enable this rule on cli with a option like `--space-function-paren`

Is the feature is accepted I will try to make a PR about.

**Comment by kentcdodds** [comment]
Hmmm... What would that flag do?

**Comment by bySabi** [comment]
Hi @kentcdodds 
I just want enable [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren)  rule on CLI without creating a `.eslintrc` file

**Comment by bySabi** [comment]
This a example of how I'm using `prettier-eslint`  [package.json](https://github.com/bySabi/npmclean/blob/master/package.json#L13)

**Comment by bySabi** [comment]
Probably is not ideal have two tools doing a similar job but I can´t not use prettier-eslint together with test script cause is more slow than `semistandard`

**Comment by kentcdodds** [comment]
> I just want enable [space-before-function-paren](http://eslint.org/docs/rules/space-before-function-paren) rule on CLI without creating a `.eslintrc` file

Sorry, but that kind of functionality is outside of the scope of this tool.

> I can't not use prettier-eslint together with test script cause is more slow than `semistandard`

Have you looked into integrating it with something like `lint-staged` (like [this](https://github.com/prettier/prettier#option-1-lint-staged))? It's a pretty great workflow. My team loves it.

Good luck to you.

**Comment by bySabi** [comment]
You are right.

I'm looking now the `--eslint-path` option for set `semistandard` engine in place of `eslint`. It seems I will need a stub module that implement ESLint CLIEngine interface. Any advice on this ? 

I look at the `lint-staged` work flow some weeks ago, is great by I'm a solo developer and my git flow is difference.

Thanks for your time

**Comment by bySabi** [comment]
@kentcdodds finally I could integrate `prettier-eslint` and `semistandard` using cli option `--eslint-path`

I publish a minimal package for make the bridge beetween `prettier` and `standard`:
 * [standard-prettier-eslint](https://github.com/bySabi/standard-prettier-eslint) for use with `standard`
 * [semistandard-prettier-eslint](https://github.com/bySabi/semistandard-prettier-eslint)  a `semistandard` version for semicolon people like me

Any feedback is wecolme.

I can submit a PR  with README tips relate to this tools. Tell me what you think.

**Comment by kentcdodds** [comment]
That's great! Yes, an addition to the README would be welcome 😀
