### ISSUE TITLE
Add --ignore-path

### ISSUE THREAD

**Issue by JosefJezek** [prettier/prettier-eslint-cli#85]
Please add option `--ignore-path` as eslint.

http://eslint.org/docs/user-guide/configuring#using-an-alternate-file

**Comment by kentcdodds** [comment]
I'd be ok with that. Feel free to [make a pull request](http://makeapullrequest.com) :+1:

**Comment by zimme** [comment]
Since version `4.6.0` we support `pretiter-ignore`.
