### ISSUE TITLE
Support for inline script in html

### ISSUE THREAD

**Issue by JosefJezek** [prettier/prettier-eslint-cli#86]
Like as https://github.com/BenoitZugmeyer/eslint-plugin-html

**Comment by kentcdodds** [comment]
Sounds great! I'd love to support that. Please feel free to [make a pull request](http://makeapullrequest.com) 😀

**Comment by zimme** [comment]
With updates to `eslint` with version `4.7` I do believe this is supported as long as `eslint-plugin-html` is using the new `preprocessor` api.
