### ISSUE TITLE
When there is unchanged (file) it exits with 0 code

### ISSUE THREAD

**Issue by tunnckoCore** [prettier/prettier-eslint-cli#88]
Hi again. I'm considering to change `lint` script directly to this CLI, because few reasons:

- 1) have StandardJS installed
- 2) have `.eslintrc.json` intentionally, which basically is `{extends: standard}`. so better IDE integration
- 3) if this CLI works properly i should get exit code 1 if something fails (somehow, for example if some contributor dont have such editor integration and just use the npm lint script)

Problem is that if there is some error it exits with code 0, which will not stop the next scripts, like `npm test` and commit.

So, i believe more correct behavior would be to exit with code 1 when even only one file is not changed (using `--write` flag). But behavior should be the same even without the `--write` flag.

**Comment by tunnckoCore** [comment]
To rephrase... My current problem is that even when ESLint finds some error this CLI exits with 0, which isn't very correct, imo. Any ideas?

Probably another tool need to be created which acts more like linter and outputs ESLint's errors, otherwise writes and formats the files. Hm. DOn't know.

**Comment by kentcdodds** [comment]
Hi @tunnckoCore :wave:

This package is not meant to replace eslint. It _only_ formats code. If the formatting was successful, then it will exit with 0. It does _not_ care about broken ESLint rules. You should use `prettier-eslint` and `eslint` together.

> Probably another tool need to be created which acts more like linter and outputs ESLint's errors, otherwise writes and formats the files.

I disagree. I think having two distinct tools for this is a good thing. But feel free to make another tool. Good luck!
