### ISSUE TITLE
slow performance. How long should it take?

### ISSUE THREAD

**Issue by jeffwillette** [prettier/prettier-eslint-cli#89]
- `prettier-eslint-cli` version: 4.1.1
- `prettier` version: 0.22.0
- `eslint` version: 4.2.0

Relevant code/config.

```javascript

```

What you did:

`prettier-eslint file.js`

What happened:

the prettier command takes less than a second and the prettier-eslint command takes about 4-5 seconds on the same file. Is this a normal execution time?

Reproduction:

-- paste your link here --

Problem description:

Suggested solution:

**Comment by kentcdodds** [comment]
Yes, prettier-eslint is fairly slow. But it shouldn't be that show (unless your file is huge or your computer is underpowered). There hasn't been a lot of effort to optimize prettier-eslint though. Would you like to look into it to try and optimize things?

**Comment by deltaskelta** [comment]
I'm afraid im not too good with the newer javascript ecosystem but I can take a look. Can you think of anything (I might have goofed something simple) that would make the process run so slow? It is a regular react project created with `create-react-app` so I do not think that the project size is an issue

**Comment by kentcdodds** [comment]
You might try some of the tips in the [troubleshooting guide](https://github.com/prettier/prettier-eslint#troubleshooting) :smile:

**Comment by Hatko** [comment]
While investigating a slow performance of eslint, I found that the most time of what it takes is `prettier/prettier`:

`TIMING=1 yarn lint`

<img width="478" alt="Screenshot 2020-05-01 at 12 09 13" src="https://user-images.githubusercontent.com/6848723/80798395-95a90180-8ba4-11ea-91a5-fb66ea342120.png">

**Comment by osdiab** [comment]
I'm also experiencing this:


<img width="590" alt="Screen Shot 2020-06-01 at 20 24 13" src="https://user-images.githubusercontent.com/1890926/83404575-dd41d800-a445-11ea-9113-c6cf720bcefa.png">

**Comment by tony** [comment]
![image](https://user-images.githubusercontent.com/26336/87167394-83c59800-c292-11ea-826e-d9ab4a14de40.png)

**Comment by firebluetom2** [comment]
![image](https://user-images.githubusercontent.com/57371057/89451459-df643380-d721-11ea-98cf-4cc28f161f2d.png)
Seeing similar

**Comment by stavalfi** [comment]
something is eating my machine:

```
 p/dancer $$ TIMING=1 yarn eslint --max-warnings 0 'packages/dancer-feed-db-api/**/*.{ts,js,json,d.ts}' --cache --fix                                                                                                                                                   932ms
yarn run v1.22.4
$ /Users/stavalfi-dev/projects/dancer/node_modules/.bin/eslint --max-warnings 0 'packages/dancer-feed-db-api/**/*.{ts,js,json,d.ts}' --cache --fix
Rule                                       | Time (ms) | Relative
:------------------------------------------|----------:|--------:
prettier/prettier                          |  2087.620 |    94.5%
unused-imports/no-unused-imports           |    19.940 |     0.9%
no-redeclare                               |    11.459 |     0.5%
@typescript-eslint/type-annotation-spacing |     6.720 |     0.3%
jest/no-identical-title                    |     5.282 |     0.2%
json/*                                     |     4.064 |     0.2%
no-misleading-character-class              |     4.025 |     0.2%
no-regex-spaces                            |     3.994 |     0.2%
@typescript-eslint/no-use-before-define    |     3.934 |     0.2%
no-empty-character-class                   |     3.763 |     0.2%
Rule | Time (ms) | Relative
:----|----------:|--------:
✨  Done in 316.94s.     <<<<<<<<<<<<<<------------------- WTF??!
```

**Comment by hpetev** [comment]
I noticed that this happens on saving even on a very small file like this one:

```
it("should pass", () => {
  expect(true).toEqual(true);
});
```

when a I save package.json before that getting an error: `Saving 'package.json': Running 'Prettier - Code formatter' Formatter (configure).` Then it becomes slow on all the files. After restart/reinstall starts working fast again until package.json is saved again.

**Comment by osdiab** [comment]
For anyone looking for workarounds, if you just run `prettier` directly instead of running it through ESLint, it runs dramatically faster.

This is what I do in `package.json`, using TypeScript with `create-react-app`:

```json
{
  "scripts": {
    "eslint": "eslint --ext \"js,ts,jsx,tsx\" ./src/@app",
    "prettier": "prettier \"src/**/*.{ts,tsx,js,jsx}\"",
    "lint": "yarn prettier --check && yarn eslint"
  }
}

```

**Comment by varemenos** [comment]
This is pretty much the most important issue for this package, could we please reopen it?
Even if it's not actively worked on?

**Comment by tony** [comment]
I'm in the same boat - on the other hand - I'm hoping someone does a Golang/Rust alternative for eslint, in general.

While this doesn't build/work yet, following this: [`deno lint`](https://github.com/denoland/deno_lint)

**Comment by jiacai2050** [comment]
https://www.reddit.com/r/neovim/comments/mrep3l/speedup_your_prettier_formatting_using_prettierd/

Prettierd seems a possible solution.
