### ISSUE TITLE
Different result compare to running `prettier` and `eslint --fix` seperately

### ISSUE THREAD

**Issue by hpb0412** [prettier/prettier-eslint-cli#90]
- `prettier-eslint-cli` version: 4.1.1
- `prettier` version: 1.5.3
- `eslint` version: 3.19.0

What you did:

`./node_modules/.bin/prettier-eslint myfile.js`

What happened:

```javascript
export {
  func1,
  func2,
  func3,
}
```
becames

```javascript
export { func1, func2, func3 }
```

If I ran `prettier myfile.js` then `eslint --fix myfile.js`, there was no transformation.
Is this the issue of `prettier-eslint`? or did I miss some settings?

**Comment by kentcdodds** [comment]
Thanks for filing this issue! Could you please dig a little deeper to see what's going on and suggest a solution to improve things? Take a look at the [troubleshooting guide](https://github.com/prettier/prettier-eslint#troubleshooting). Thanks again!

**Comment by hpb0412** [comment]
@kentcdodds I finally found that I needed explicitly set `--print-width` to 80. Look like the default is around 100.

**Comment by kentcdodds** [comment]
Sounds good. Thanks!
