### ISSUE TITLE
fix: update to eslint 4.0

### ISSUE THREAD

**Issue by BerkeleyTrue** [prettier/prettier-eslint-cli#94]
- `prettier-eslint-cli` version: 4.2.1
- `prettier` version: 1.5.3
- `eslint` version: 4.5.0

Relevant code/config.

```javascript
  "indent": [ "error", 2, { "SwitchCase": 1, "ignoredNodes": [ "JSXElement", "JSXOpeningElement" ] } ]
```

```bash
prettier-eslint 'src/**/*.js' --eslint-config-path ./.eslintrc --trailing-comma all --single-quote --write
```

What you did:
run prettier eslint using eslintrc for current version of eslint

What happened:

![1__tmux](https://user-images.githubusercontent.com/6775919/29597039-0326dd18-8775-11e7-8ac4-0ee7f2ae99d6.png)

Reproduction:

Add the above `indent` rule to your eslintrc. Run prettier-eslint-cli on a file

-- paste your link here --

Problem description:

The current version of prettier-eslint-cli uses a previous version of eslint. The current version of eslint has additional rules that are not available to prettier-eslint-cli, which causes it to fail.

Suggested solution:

* Update internal version of eslint

This isn't critical for me as I believe I can just run prettier first then run eslint --fix consecutively.

I also see some indication that you are using greenkeeper yet I couldn't find a PR for version 4 of eslint.

**Comment by kentcdodds** [comment]
Thanks for the report. Could you make a pull request for this?

I don't like greenkeeper (I've used it before). Thanks for your help!
