### ISSUE TITLE
 Is the goal of this project to provide a drop-in replacement for prettier when working with eslint?

### ISSUE THREAD

**Issue by eqyiel** [prettier/prettier-eslint-cli#95]
`prettier-eslint-cli` lacks a `--stdin-filepath` option.  This is breaking `prettier` editor integrations because `prettier-eslint-cli` doesn't provide the same API, see the discussion here for details: https://github.com/prettier/prettier-emacs/pull/10

I don't mind attempting a PR but I'd like to see what people think about this first.

Even if a change like this would be up for consideration I'm not sure what the behaviour of `--stdin-filepath` should be for `prettier-eslint-cli` considering that `prettier` uses it for parser inference and `prettier-eslint-cli` is focused on JS.

IMHO the least surprising result would be to defer to `prettier` for non-JS files, but I don't know if that is an option unless the allowed arguments for `prettier-eslint-cli` are a strict superset of those for `prettier`.

**Comment by kentcdodds** [comment]
Thanks! I'd love a pull request to add that flag. Should be rather simple. 👍

**Comment by eqyiel** [comment]
The team I work with is moving to using vanilla prettier and I'm no longer motivated to work on this, so I'm closing it.

Thanks for your support and work on this project @kentcdodds. 😊
